// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYmNG8nO3dfPCzh2gZ8qbu6Wjspy29DnA',
    appId: '1:432013570109:web:237af5ab028de5d2b17a54',
    messagingSenderId: '432013570109',
    projectId: 'vidic-8478f',
    authDomain: 'vidic-8478f.firebaseapp.com',
    storageBucket: 'vidic-8478f.appspot.com',
    measurementId: 'G-5E95T87D02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw0zqr9kjTL5DTAnbRF7MYkHbOoFd0lT8',
    appId: '1:432013570109:android:fd0ef06d493844fbb17a54',
    messagingSenderId: '432013570109',
    projectId: 'vidic-8478f',
    storageBucket: 'vidic-8478f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqs5-RUxC_TJl95cMR4t5v1mqyBDzgR78',
    appId: '1:432013570109:ios:984524d4babd60c9b17a54',
    messagingSenderId: '432013570109',
    projectId: 'vidic-8478f',
    storageBucket: 'vidic-8478f.appspot.com',
    iosClientId: '432013570109-e20c729ui92e2s5g3k6ritfh7a0s5e3t.apps.googleusercontent.com',
    iosBundleId: 'com.vidicvictoria.vidic',
  );
}
